networks:
  gitea:
    external: false

volumes:
  gitea:
    driver: local
  postgres:
    driver: local

services:
  gitea:
    image: docker.gitea.com/gitea:1.23.7-rootless
    container_name: gitea-rootless
    user: 1000:1000  # Run as non-root user
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea_password
      # External access configuration
      - GITEA__server__DOMAIN=localhost
      - GITEA__server__ROOT_URL=http://${EXTERNAL_IP}:3000/
      - GITEA__server__SSH_DOMAIN=${EXTERNAL_IP}
      # Use non-privileged ports for rootless
      - GITEA__server__HTTP_PORT=3000
      - GITEA__server__SSH_PORT=2222  # Non-privileged port for SSH
      - GITEA__server__SSH_LISTEN_PORT=2222
    restart: always
    networks:
      - gitea
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"  # Web interface
      - "2222:2222"  # SSH for git operations (non-privileged port)
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: gitea-db-rootless
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea_password
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - postgres:/var/lib/postgresql/data